# Generated by Django 4.0.4 on 2022-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_app", "0002_alter_contact_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
