# Generated by Django 4.0.4 on 2022-06-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_app", "0004_remove_contact_birthday_lifeevent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LifeEvent",
            new_name="Milestone",
        ),
    ]
