# Generated by Django 4.0.4 on 2022-06-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_app", "0005_rename_lifeevent_milestone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milestone",
            name="notify",
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
