# Generated by Django 4.0.4 on 2022-06-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_app", "0006_remove_milestone_notify_alter_contact_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notify_after",
            field=models.IntegerField(default=0),
        ),
    ]
